# Spanish (es) translations for Typus by:
# - Felipe Talavera <http://github.com/flype>

es:
  activerecord:
    models:
      admin_user:
    attributes:
      admin_user:
        email: "Correo electrónico"
        first_name: "Nombre"
        last_name: "Apellidos"
        password: "Contraseña"
        password_confirmation: "Confirmar contraseña"
        status: "Estado"
        role: "Rol"
